#!bin/bash

# Used in: Step 11. Decontaminate
## The jobs were stuck and there was no writing in the destination directory for some time now.
## Stragglers were identified by looking at both the indir ("../fq_fp1_clmp_fp2") and outdir ("../fq_fp1_clmp_fp2_fqscrn").
## These are the missing files:

### Sor-ABur_007-Ex1-12G-lcwgs-1-T.clmp.fp2_r2
### Sor-ABur_010-Ex1-3H-lcwgs-1-T.clmp.fp2_r2
### Sor-ABur_011-Ex1-4H-lcwgs-1-T.clmp.fp2_r1
### Sor-ABur_011-Ex1-4H-lcwgs-1-T.clmp.fp2_r2
### Sor-ABur_012-Ex1-5H-lcwgs-1-T.clmp.fp2_r2


sequence_dir="/home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/sphaeramia_orbicularis/fq_raw"
#seqID=("SoC0301809F" "SoC0301809G" "SoC0301809H") # This only records G and H, not F, which is weird.
seqID=("SoC0301809")
outfile="delete_seq.out"

for file in $(find $sequence_dir -name "*.fq.gz"); do
	for seqID in "${seqID[@]}"; do
		if [[ $file =~ $seqID ]]; then
			echo "Deleting file: $file" >> $outfile
			rm -i $file
			break
		fi
	done
done


