#!/bin/bash -l

#SBATCH --job-name=mkBAM2
#SBATCH -o mkBAM2-%j.out
#SBATCH --time=00:00:00
#SBATCH --cpus-per-task=40
#SBATCH --exclusive=user

enable_lmod
module load container_env ddocent/2.9.4

export SINGULARITY_BIND=/home/e1garcia
export PARALLEL_SHELL=/bin/bash

# crun.ddocent bwa-meme
# crun.ddocent bwa

#FUNCTION=$1
CONFIG=$1

#crun.ddocent bash ../../../dDocentHPC/dDocentHPC_dev2.bash mkBAM $CONFIG
#crun.ddocent bash ../../../dDocentHPC/dDocentHPC_dev2.bash fltrBAM $CONFIG
crun.ddocent bash /home/e1garcia/shotgun_PIRE/dDocentHPC/dDocentHPC.bash mkBAM $CONFIG

