# -*- mode: Yaml; -*-
# Default options.
# Can also be specific for a set of samples, libraries, and lanes,
# by including the "Options" hierarchy at the same level as those
# samples, libraries, or lanes below.
Options:
  # Sequencing platform, see SAM/BAM reference for valid values
  Platform: Illumina
  # Quality offset for Phred scores, either 33 (Sanger/Illumina 1.8+)
  # or 64 (Illumina 1.3+ / 1.5+). For Bowtie2 it is also possible to
  # specify 'Solexa', to handle reads on the Solexa scale. This is
  # used during adapter-trimming and sequence alignment
  QualityOffset: 33

  # Settings for trimming of reads, see AdapterRemoval man-page
  AdapterRemoval:
    # Set and uncomment to override defaults adapter sequences
#     --adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG
#     --adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
    # Some BAM pipeline defaults differ from AR defaults;
    # To override, change these value(s):
    --mm: 3
    --minlength: 25
    # Extra features enabled by default; change 'yes' to 'no' to disable
    --collapse: yes
    --trimns: yes
    --trimqualities: yes

  # Settings for aligners supported by the pipeline
  Aligners:
    # Choice of aligner software to use, either "BWA" or "Bowtie2"
    Program: BWA

    # Settings for mappings performed using BWA
    BWA:
      # One of "backtrack", "bwasw", or "mem"; see the BWA documentation
      # for a description of each algorithm (defaults to 'backtrack')
      Algorithm: backtrack
      # Filter aligned reads with a mapping quality (Phred) below this value
      MinQuality: 30
      # Filter reads that did not map to the reference sequence
      FilterUnmappedReads: yes
      # May be disabled ("no") for aDNA alignments with the 'aln' algorithm.
      # Post-mortem damage localizes to the seed region, which BWA expects to
      # have few errors (sets "-l"). See http://pmid.us/22574660
      UseSeed: no
      # Additional command-line options may be specified below. For 'backtrack' these
      # are applied to the "bwa aln". See Bowtie2 for more examples.
#      -n: 0.04

    # Settings for mappings performed using Bowtie2
    Bowtie2:
      # Filter aligned reads with a mapping quality (Phred) below this value
      MinQuality: 0
      # Filter reads that did not map to the reference sequence
      FilterUnmappedReads: yes
      # Examples of how to add additional command-line options
#      --trim5: 5
#      --trim3: 5
      # Note that the colon is required, even if no value is specified
      --very-sensitive:
      # Example of how to specify multiple values for an option
#      --rg:
#        - CN:SequencingCenterNameHere
#        - DS:DescriptionOfReadGroup

  # Command-line options for mapDamage; use long-form options(--length not -l):
  mapDamage:
    # By default, the pipeline will downsample the input to 100k hits
    # when running mapDamage; remove to use all hits
    --downsample: 100000

  # Set to 'yes' exclude a type of trimmed reads from alignment / analysis;
  # possible read-types reflect the output of AdapterRemoval
  ExcludeReads:
    # Exclude single-end reads (yes / no)?
    Single: no
    # Exclude non-collapsed paired-end reads (yes / no)?
    Paired: no
    # Exclude paired-end reads for which the mate was discarded (yes / no)?
    Singleton: no
    # Exclude overlapping paired-ended reads collapsed into a single sequence
    # by AdapterRemoval (yes / no)?
    Collapsed: no
    # Like 'Collapsed', but only for collapsed reads truncated due to the
    # presence of ambiguous or low quality bases at read termini (yes / no).
    CollapsedTruncated: no

  # Optional steps to perform during processing.
  Features:
    # If set to 'filter', PCR duplicates are removed from the output files; if set to
    # 'mark', PCR duplicates are flagged with bit 0x400, and not removed from the
    # output files; if set to 'no', the reads are assumed to not have been amplified.
    PCRDuplicates: filter
    # Set to 'no' to disable mapDamage; set to 'plots' to build basic mapDamage plots;
    # set to 'model' to build plots and post-mortem damage models; and set to 'rescale'
    # to build plots, models, and BAMs with rescaled quality scores. All analyses are
    # carried out per library.
    mapDamage: rescale
    # Generate coverage information for the final BAM and for each 'RegionsOfInterest'
    # specified in 'Prefixes' (yes / no).
    Coverage: yes
    # Generate histograms of number of sites with a given read-depth, from 0 to 200,
    # for each BAM and for each 'RegionsOfInterest' specified in 'Prefixes' (yes / no).
    Depths: yes
    # Generate summary table for each target (yes / no)
    Summary: yes


# Map of prefixes by name, each having a Path, which specifies the location of the
# BWA/Bowtie2 index, and optional regions for which additional statistics are produced.
Prefixes:
  # Replace 'NAME_OF_PREFIX' with name of the prefix; this name is used in summary
  # statistics and as part of output filenames.
  Sfa:
    Path: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/refGenome/GCF_902148845.1_fSalaFa1.1_chr1-23-mtgen.fasta


Sfa_lcWGS:
  Sfa-ABas_001:
    Sfa-ABas_001_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_001_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_013:
    Sfa-ABas_013_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_013_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_025:
    Sfa-ABas_025_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_025_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_002:
    Sfa-ABas_002_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_002_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_014:
    Sfa-ABas_014_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_014_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_026:
    Sfa-ABas_026_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_026_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_003:
    Sfa-ABas_003_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_003_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_027:
    Sfa-ABas_027_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_027_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_004:
    Sfa-ABas_004_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_004_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_016:
    Sfa-ABas_016_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_016_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_028:
    Sfa-ABas_028_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_028_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_005:
    Sfa-ABas_005_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_005_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_017:
    Sfa-ABas_017_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_017_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_029:
    Sfa-ABas_029_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_029_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_006:
    Sfa-ABas_006_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_006_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_018:
    Sfa-ABas_018_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_018_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_030:
    Sfa-ABas_030_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_030_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_007:
    Sfa-ABas_007_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_007_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_019:
    Sfa-ABas_019_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_019_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_031:
    Sfa-ABas_031_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_031_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_008:
    Sfa-ABas_008_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_008_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_020:
    Sfa-ABas_020_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_020_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_032:
    Sfa-ABas_032_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_032_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_009:
    Sfa-ABas_009_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_009_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_021:
    Sfa-ABas_021_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_021_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_033:
    Sfa-ABas_033_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_033_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_010:
    Sfa-ABas_010_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_010_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_022:
    Sfa-ABas_022_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_022_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_034:
    Sfa-ABas_034_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_034_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_023:
    Sfa-ABas_023_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_023_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_035:
    Sfa-ABas_035_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_035_Ex1_L3_{Pair}.fq.gz


  Sfa-ABas_024:
    Sfa-ABas_024_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-ABas_024_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_088:
    Sfa-CBas_088_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_088_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_066:
    Sfa-CBas_066_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_066_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_061:
    Sfa-CBas_061_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_061_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_017:
    Sfa-CBas_017_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_017_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_033:
    Sfa-CBas_033_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_033_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_078:
    Sfa-CBas_078_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_078_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_003:
    Sfa-CBas_003_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_003_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_067:
    Sfa-CBas_067_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_067_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_002:
    Sfa-CBas_002_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_002_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_076:
    Sfa-CBas_076_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_076_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_084:
    Sfa-CBas_084_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_084_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_036:
    Sfa-CBas_036_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_036_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_048:
    Sfa-CBas_048_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_048_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_086:
    Sfa-CBas_086_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_086_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_023:
    Sfa-CBas_023_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_023_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_008:
    Sfa-CBas_008_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_008_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_019:
    Sfa-CBas_019_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_019_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_091:
    Sfa-CBas_091_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_091_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_027:
    Sfa-CBas_027_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_027_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_001:
    Sfa-CBas_001_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_001_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_029:
    Sfa-CBas_029_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_029_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_041:
    Sfa-CBas_041_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_041_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_010:
    Sfa-CBas_010_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_010_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_026:
    Sfa-CBas_026_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_026_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_009:
    Sfa-CBas_009_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_009_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_043:
    Sfa-CBas_043_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_043_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_062:
    Sfa-CBas_062_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_062_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_020:
    Sfa-CBas_020_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_020_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_042:
    Sfa-CBas_042_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_042_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_015:
    Sfa-CBas_015_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_015_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_007:
    Sfa-CBas_007_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_007_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_032:
    Sfa-CBas_032_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_032_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_031:
    Sfa-CBas_031_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_031_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_016:
    Sfa-CBas_016_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_016_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_059:
    Sfa-CBas_059_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_059_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_030:
    Sfa-CBas_030_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_030_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_014:
    Sfa-CBas_014_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_014_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_021:
    Sfa-CBas_021_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_021_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_028:
    Sfa-CBas_028_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_028_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_056:
    Sfa-CBas_056_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_056_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_025:
    Sfa-CBas_025_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_025_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_044:
    Sfa-CBas_044_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_044_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_073:
    Sfa-CBas_073_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_073_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_039:
    Sfa-CBas_039_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_039_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_046:
    Sfa-CBas_046_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_046_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_092:
    Sfa-CBas_092_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_092_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_006:
    Sfa-CBas_006_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_006_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_090:
    Sfa-CBas_090_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_090_Ex1_L3_{Pair}.fq.gz


  Sfa-CBas_096:
    Sfa-CBas_096_Lib1:
      Lane_1: /home/e1garcia/shotgun_PIRE/pire_lcwgs_data_processing/salarias_fasciatus/1st_sequencing_run/fq_raw/Sfa-CBas_096_Ex1_L3_{Pair}.fq.gz


